### ISSUE TITLE
Cloud issue

### ISSUE THREAD

**Issue by ohan-Bioinfo** [dbmi-bgm/xTea-germline#1]
Google cloud or terra can accept only WDL script i have been trying to convert WCL into a WDL for awhile but never succeeded, would you please have a look,

My WDL script obtained from WCL:

```

workflow Xtea {
    call Transposable_Element
}   


task Transposable_Element {
    File input_bam
    Int analysis_type
    File genome_tar
    File repeats_tar
    File Annotation
    String sample
        command {
            python /usr/local/bin/gnrt_pipeline_germline_cloud_v38.py -D -f 5907 -n 4 --xtea /usr/local/bin/ -o run_jobs.sh -p . \
            -b ${input_bam} \
            -y ${default='1' analysis_type} \
            -r ${genome_tar} \
            -l ${repeats_tar} \
            -g ${Annotation} \
            -i ${sample} 
        }
        runtime {
    	    cpu: 4
  	    	memory: "24GB"
            disks: "local-disk 501 HDD"
            docker: "cgap/xtea_germline:v0.1.9"
        }
        output {
        	File results= "${sample}.Transposable_Element.results"
        }

}

```

Log Error 

```
2022/10/19 11:02:27 Starting container setup.
2022/10/19 11:02:29 Done container setup.
2022/10/19 11:02:31 Starting localization.
2022/10/19 11:02:42 Localization script execution started...
2022/10/19 11:02:42 Localizing input gs://fc-00bcc31d-9daf-40fa-bca6-2c6aa332a71c/submissions/4bf630ee-902d-4d1a-b9bb-e202966979e2/Xtea/e3ecdb6a-69dc-4763-92af-5cc1b7a640de/call-Transposable_Element/script -> /cromwell_root/script
2022/10/19 11:02:46 Localizing input gs://fc-00bcc31d-9daf-40fa-bca6-2c6aa332a71c/NDX-22-829-004.bam -> /cromwell_root/fc-00bcc31d-9daf-40fa-bca6-2c6aa332a71c/NDX-22-829-004.bam
2022/10/19 11:05:25 Localizing input gs://fc-00bcc31d-9daf-40fa-bca6-2c6aa332a71c/gencode.v33.annotation.gff3.gz -> /cromwell_root/fc-00bcc31d-9daf-40fa-bca6-2c6aa332a71c/gencode.v33.annotation.gff3.gz
2022/10/19 11:05:25 Localizing input gs://fc-00bcc31d-9daf-40fa-bca6-2c6aa332a71c/GRCh38.p13.genome.fa.gz.tar -> /cromwell_root/fc-00bcc31d-9daf-40fa-bca6-2c6aa332a71c/GRCh38.p13.genome.fa.gz.tar
2022/10/19 11:05:25 Localizing input gs://fc-00bcc31d-9daf-40fa-bca6-2c6aa332a71c/rep_lib_annotation.tar.gz -> /cromwell_root/fc-00bcc31d-9daf-40fa-bca6-2c6aa332a71c/rep_lib_annotation.tar.gz
Copying gs://fc-00bcc31d-9daf-40fa-bca6-2c6aa332a71c/gencode.v33.annotation.gff3.gz...
/ [0 files][ 0.0 B/ 50.1 MiB] - - [1 files][ 50.1 MiB/ 50.1 MiB] Copying gs://fc-00bcc31d-9daf-40fa-bca6-2c6aa332a71c/GRCh38.p13.genome.fa.gz.tar...
- [1 files][ 50.1 MiB/ 50.1 MiB] - [2 files][ 50.1 MiB/ 50.1 MiB] Copying gs://fc-00bcc31d-9daf-40fa-bca6-2c6aa332a71c/rep_lib_annotation.tar.gz...
- [2 files][ 50.1 MiB/350.3 MiB] \ | | [2 files][ 91.1 MiB/350.3 MiB] / / [2 files][158.1 MiB/350.3 MiB] - \ \ [2 files][214.4 MiB/350.3 MiB] | / / [2 files][278.8 MiB/350.3 MiB] - - [2 files][344.1 MiB/350.3 MiB] \
Operation completed over 3 objects/350.3 MiB.
\ [3 files][350.3 MiB/350.3 MiB] 2022/10/19 11:05:34 Localization script execution complete.
2022/10/19 11:05:39 Done localization.
2022/10/19 11:05:40 Running user action: docker run -v /mnt/local-disk:/cromwell_root --entrypoint=/bin/bash cgap/xtea_germline@sha256:e41de242a17adf5f11d2ebb66861f61a1fb19a4af14183c3db302b0645e97f7d /cromwell_root/script
multiprocessing.pool.RemoteTraceback:
"""
Traceback (most recent call last):
File "/miniconda/lib/python3.8/multiprocessing/pool.py", line 125, in worker
result = (True, func(*args, **kwds))
File "/miniconda/lib/python3.8/multiprocessing/pool.py", line 48, in mapstar
return list(map(*args))
File "/usr/local/bin/clip_read.py", line 41, in unwrap_self_cnt_clip_pos
return ClipReadInfo.collect_clip_positions_by_chrm(*arg, **kwarg)
File "/usr/local/bin/clip_read.py", line 311, in collect_clip_positions_by_chrm
xannotation.load_rmsk_annotation_with_extnd_with_lenth_cutoff(i_boundary_extnd, i_min_copy_len)
File "/usr/local/bin/x_annotation.py", line 330, in load_rmsk_annotation_with_extnd_with_lenth_cutoff
with open(self.sf_annotation) as fin_rmsk:
FileNotFoundError: [Errno 2] No such file or directory: '/cromwell_root/rep_lib_annotation/LINE/hg38/hg38_L1_larger_500_with_all_L1HS.out'
"""

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
File "/usr/local/bin/x_TEA_main_germline_cloud.py", line 424, in <module>
tem_locator.call_TEI_candidate_sites_from_multiple_alignmts(sf_annotation, sf_rep_cns, sf_rep, b_se,
File "/usr/local/bin/x_TEI_locator.py", line 107, in call_TEI_candidate_sites_from_multiple_alignmts
caller.call_TEI_candidate_sites_from_clip_reads_v2(sf_annotation, sf_rep_cns, sf_ref, b_se,
File "/usr/local/bin/x_TEI_locator.py", line 616, in call_TEI_candidate_sites_from_clip_reads_v2
clip_info.collect_clip_positions(sf_annotation, initial_clip_pos_freq_cutoff, b_se, sf_pub_folder) ##save clip pos by chrm
File "/usr/local/bin/clip_read.py", line 419, in collect_clip_positions
pool.map(unwrap_self_cnt_clip_pos, list(zip([self] * len(l_chrm_records), l_chrm_records)), 1)
File "/miniconda/lib/python3.8/multiprocessing/pool.py", line 364, in map
return self._map_async(func, iterable, mapstar, chunksize).get()
File "/miniconda/lib/python3.8/multiprocessing/pool.py", line 771, in get
raise self._value
FileNotFoundError: [Errno 2] No such file or directory: '/cromwell_root/rep_lib_annotation/LINE/hg38/hg38_L1_larger_500_with_all_L1HS.out'
multiprocessing.pool.RemoteTraceback:
"""
Traceback (most recent call last):
File "/miniconda/lib/python3.8/multiprocessing/pool.py", line 125, in worker
result = (True, func(*args, **kwds))
File "/miniconda/lib/python3.8/multiprocessing/pool.py", line 48, in mapstar
return list(map(*args))
File "/usr/local/bin/clip_read.py", line 41, in unwrap_self_cnt_clip_pos
return ClipReadInfo.collect_clip_positions_by_chrm(*arg, **kwarg)
File "/usr/local/bin/clip_read.py", line 311, in collect_clip_positions_by_chrm
xannotation.load_rmsk_annotation_with_extnd_with_lenth_cutoff(i_boundary_extnd, i_min_copy_len)
File "/usr/local/bin/x_annotation.py", line 330, in load_rmsk_annotation_with_extnd_with_lenth_cutoff
with open(self.sf_annotation) as fin_rmsk:
FileNotFoundError: [Errno 2] No such file or directory: '/cromwell_root/rep_lib_annotation/Alu/hg38/hg38_Alu.out'
"""

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
File "/usr/local/bin/x_TEA_main_germline_cloud.py", line 424, in <module>
tem_locator.call_TEI_candidate_sites_from_multiple_alignmts(sf_annotation, sf_rep_cns, sf_rep, b_se,
File "/usr/local/bin/x_TEI_locator.py", line 107, in call_TEI_candidate_sites_from_multiple_alignmts
caller.call_TEI_candidate_sites_from_clip_reads_v2(sf_annotation, sf_rep_cns, sf_ref, b_se,
File "/usr/local/bin/x_TEI_locator.py", line 616, in call_TEI_candidate_sites_from_clip_reads_v2
clip_info.collect_clip_positions(sf_annotation, initial_clip_pos_freq_cutoff, b_se, sf_pub_folder) ##save clip pos by chrm
File "/usr/local/bin/clip_read.py", line 419, in collect_clip_positions
pool.map(unwrap_self_cnt_clip_pos, list(zip([self] * len(l_chrm_records), l_chrm_records)), 1)
File "/miniconda/lib/python3.8/multiprocessing/pool.py", line 364, in map
return self._map_async(func, iterable, mapstar, chunksize).get()
File "/miniconda/lib/python3.8/multiprocessing/pool.py", line 771, in get
raise self._value
FileNotFoundError: [Errno 2] No such file or directory: '/cromwell_root/rep_lib_annotation/Alu/hg38/hg38_Alu.out'
multiprocessing.pool.RemoteTraceback:
"""
Traceback (most recent call last):
File "/miniconda/lib/python3.8/multiprocessing/pool.py", line 125, in worker
result = (True, func(*args, **kwds))
File "/miniconda/lib/python3.8/multiprocessing/pool.py", line 48, in mapstar
return list(map(*args))
File "/usr/local/bin/clip_read.py", line 41, in unwrap_self_cnt_clip_pos
return ClipReadInfo.collect_clip_positions_by_chrm(*arg, **kwarg)
File "/usr/local/bin/clip_read.py", line 311, in collect_clip_positions_by_chrm
xannotation.load_rmsk_annotation_with_extnd_with_lenth_cutoff(i_boundary_extnd, i_min_copy_len)
File "/usr/local/bin/x_annotation.py", line 330, in load_rmsk_annotation_with_extnd_with_lenth_cutoff
with open(self.sf_annotation) as fin_rmsk:
FileNotFoundError: [Errno 2] No such file or directory: '/cromwell_root/rep_lib_annotation/SVA/hg38/hg38_SVA.out'
"""

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
File "/usr/local/bin/x_TEA_main_germline_cloud.py", line 424, in <module>
tem_locator.call_TEI_candidate_sites_from_multiple_alignmts(sf_annotation, sf_rep_cns, sf_rep, b_se,
File "/usr/local/bin/x_TEI_locator.py", line 107, in call_TEI_candidate_sites_from_multiple_alignmts
caller.call_TEI_candidate_sites_from_clip_reads_v2(sf_annotation, sf_rep_cns, sf_ref, b_se,
File "/usr/local/bin/x_TEI_locator.py", line 616, in call_TEI_candidate_sites_from_clip_reads_v2
clip_info.collect_clip_positions(sf_annotation, initial_clip_pos_freq_cutoff, b_se, sf_pub_folder) ##save clip pos by chrm
File "/usr/local/bin/clip_read.py", line 419, in collect_clip_positions
pool.map(unwrap_self_cnt_clip_pos, list(zip([self] * len(l_chrm_records), l_chrm_records)), 1)
File "/miniconda/lib/python3.8/multiprocessing/pool.py", line 364, in map
return self._map_async(func, iterable, mapstar, chunksize).get()
File "/miniconda/lib/python3.8/multiprocessing/pool.py", line 771, in get
raise self._value
FileNotFoundError: [Errno 2] No such file or directory: '/cromwell_root/rep_lib_annotation/SVA/hg38/hg38_SVA.out'
Finished indexing bam files
tar -zxvf /cromwell_root/fc-00bcc31d-9daf-40fa-bca6-2c6aa332a71c/rep_lib_annotation.tar.gz -C /cromwell_root/
tar -zxvf /cromwell_root/fc-00bcc31d-9daf-40fa-bca6-2c6aa332a71c/GRCh38.p13.genome.fa.gz.tar -C /cromwell_root/
Start command generating:
Generate family folder: /cromwell_root/Exom-Tes-Test
mkdir /cromwell_root/Exom-Tes-Test/LINE1
Sample id file: /cromwell_root/Exom-Tes-Test/LINE1/sample_id.txt
mkdir /cromwell_root/Exom-Tes-Test/ALU
Sample id file: /cromwell_root/Exom-Tes-Test/ALU/sample_id.txt
mkdir /cromwell_root/Exom-Tes-Test/SVA
Sample id file: /cromwell_root/Exom-Tes-Test/SVA/sample_id.txt
mkdir /cromwell_root/Exom-Tes-Test/LINE1//tmp
mkdir /cromwell_root/Exom-Tes-Test/LINE1//tmp/clip
mkdir /cromwell_root/Exom-Tes-Test/LINE1//tmp/cns
mkdir /cromwell_root/Exom-Tes-Test/LINE1//tmp/cns/asm
mkdir /cromwell_root/Exom-Tes-Test/LINE1//tmp/transduction
mkdir /cromwell_root/Exom-Tes-Test/LINE1//tmp/igv
mkdir /cromwell_root/Exom-Tes-Test/ALU//tmp
mkdir /cromwell_root/Exom-Tes-Test/ALU//tmp/clip
mkdir /cromwell_root/Exom-Tes-Test/ALU//tmp/cns
mkdir /cromwell_root/Exom-Tes-Test/ALU//tmp/cns/asm
mkdir /cromwell_root/Exom-Tes-Test/ALU//tmp/transduction
mkdir /cromwell_root/Exom-Tes-Test/ALU//tmp/igv
mkdir /cromwell_root/Exom-Tes-Test/SVA//tmp
mkdir /cromwell_root/Exom-Tes-Test/SVA//tmp/clip
mkdir /cromwell_root/Exom-Tes-Test/SVA//tmp/cns
mkdir /cromwell_root/Exom-Tes-Test/SVA//tmp/cns/asm
mkdir /cromwell_root/Exom-Tes-Test/SVA//tmp/transduction
mkdir /cromwell_root/Exom-Tes-Test/SVA//tmp/igv
List of command:

['/cromwell_root/Exom-Tes-Test/LINE1/run_xTEA_pipeline.sh', '/cromwell_root/Exom-Tes-Test/ALU/run_xTEA_pipeline.sh', '/cromwell_root/Exom-Tes-Test/SVA/run_xTEA_pipeline.sh']
Start run the generated command:
sh /cromwell_root/Exom-Tes-Test/run_xTea_germline_ins.sh
Finished running command, begin to compress files
mkdir /cromwell_root/Exom-Tes-Test_results/
mkdir /cromwell_root/Exom-Tes-Test_results/LINE1/
mkdir /cromwell_root/Exom-Tes-Test_results/LINE1/Exom-Tes-Test/
tar -cvzf /cromwell_root/Exom-Tes-Test_LINE1.tar.gz -C /cromwell_root/Exom-Tes-Test_results/ .
mkdir /cromwell_root/Exom-Tes-Test_results/ALU/
mkdir /cromwell_root/Exom-Tes-Test_results/ALU/Exom-Tes-Test/
tar -cvzf /cromwell_root/Exom-Tes-Test_ALU.tar.gz -C /cromwell_root/Exom-Tes-Test_results/ .
mkdir /cromwell_root/Exom-Tes-Test_results/SVA/
mkdir /cromwell_root/Exom-Tes-Test_results/SVA/Exom-Tes-Test/
tar -cvzf /cromwell_root/Exom-Tes-Test_SVA.tar.gz -C /cromwell_root/Exom-Tes-Test_results/ .
Finished results compression
2022/10/19 11:12:00 Starting delocalization.
2022/10/19 11:12:01 Delocalization script execution started...
2022/10/19 11:12:01 Delocalizing output /cromwell_root/memory_retry_rc -> gs://fc-00bcc31d-9daf-40fa-bca6-2c6aa332a71c/submissions/4bf630ee-902d-4d1a-b9bb-e202966979e2/Xtea/e3ecdb6a-69dc-4763-92af-5cc1b7a640de/call-Transposable_Element/memory_retry_rc
2022/10/19 11:12:04 Delocalizing output /cromwell_root/rc -> gs://fc-00bcc31d-9daf-40fa-bca6-2c6aa332a71c/submissions/4bf630ee-902d-4d1a-b9bb-e202966979e2/Xtea/e3ecdb6a-69dc-4763-92af-5cc1b7a640de/call-Transposable_Element/rc
2022/10/19 11:12:06 Delocalizing output /cromwell_root/stdout -> gs://fc-00bcc31d-9daf-40fa-bca6-2c6aa332a71c/submissions/4bf630ee-902d-4d1a-b9bb-e202966979e2/Xtea/e3ecdb6a-69dc-4763-92af-5cc1b7a640de/call-Transposable_Element/stdout
2022/10/19 11:12:08 Delocalizing output /cromwell_root/stderr -> gs://fc-00bcc31d-9daf-40fa-bca6-2c6aa332a71c/submissions/4bf630ee-902d-4d1a-b9bb-e202966979e2/Xtea/e3ecdb6a-69dc-4763-92af-5cc1b7a640de/call-Transposable_Element/stderr
2022/10/19 11:12:10 Delocalizing output /cromwell_root/Exom-Tes-Test.Transposable_Element.results -> gs://fc-00bcc31d-9daf-40fa-bca6-2c6aa332a71c/submissions/4bf630ee-902d-4d1a-b9bb-e202966979e2/Xtea/e3ecdb6a-69dc-4763-92af-5cc1b7a640de/call-Transposable_Element/Exom-Tes-Test.Transposable_Element.results
Required file output '/cromwell_root/Exom-Tes-Test.Transposable_Element.results' does not exist.
```

**Comment by B3rse** [comment]
Hi, 

This repo is still a bit of a work in progress and it's customized for our cloud infrastructure. If this doesn't work for you, you may want to check the original code (https://github.com/parklab/xTea) and set up your WDL and Docker from scratch.

However, from the log you posted looks like there may be some problem in how the reference files are mounted.

I think the files are mounted here:

`2022/10/19 11:05:25 Localizing input gs://fc-00bcc31d-9daf-40fa-bca6-2c6aa332a71c/rep_lib_annotation.tar.gz -> /cromwell_root/fc-00bcc31d-9daf-40fa-bca6-2c6aa332a71c/rep_lib_annotation.tar.gz`

and there is differences in where the software it's actually looking for the files, and can't find the file throwing the error:

`FileNotFoundError: [Errno 2] No such file or directory: '/cromwell_root/rep_lib_annotation/`

I am not the original developer of the software so I am not really sure if that is a software issue or just a WDL setup issue in how the files are mounted into the docker. Maybe you can just mount the files in the expected path?

Hope this helps,

Best

**Comment by B3rse** [comment]
another possibility is that `repeats_tar` probably is referencing the wrong file or location maybe? 

Best

**Comment by ohan-Bioinfo** [comment]
Thank you for your response

All input are in the right place i assume

**Comment by ohan-Bioinfo** [comment]
i have created my own docker image earlier with all dependencies and i end up with much more errors, 

this is the command can you predict anything wrong 

            
 
`  python /usr/local/bin/gnrt_pipeline_germline_cloud_v38.py -i ${sample} -D -b ${input_bam} -x /usr/local/bin/ -p /usr/local/bin/ -o /usr/local/bin/ -n 18  -l ${repeats_tar} -r ${genome_tar} -g ${Annotation} -f 5907  -y 1 `

**Comment by ohan-Bioinfo** [comment]
if i use -D flag both the reference and the repeat libraries should be compressed 

Running the docker image locally to investigate: i have a question regarding repeat config flag as stated below
Should i provide the comprised repeats library or any preparation need it?
what it means config file for repeat and i looked everywhere no config file found? 
```
oot@05c6a12243f0:/usr/local/bin# python gnrt_pipeline_germline_cloud_v38.py -h
Usage: gnrt_pipeline_germline_cloud_v38.py [options]

Options:
  -h, --help            show this help message and exit
  -D, --decompress      Decompress the rep lib and reference file
  -i FILE, --id=FILE    sample id list file
  -a FILE, --par=FILE   parameter file
  -l FILE, --lib=FILE   TE lib **config file**
```
