### ISSUE TITLE
Error Python

### ISSUE THREAD

**Issue by ohan-Bioinfo** [dbmi-bgm/xTea-germline#2]
any explanation of this failure:

```
Traceback (most recent call last):
File "/miniconda/lib/python3.8/multiprocessing/pool.py", line 125, in worker
result = (True, func(*args, **kwds))
File "/miniconda/lib/python3.8/multiprocessing/pool.py", line 48, in mapstar
return list(map(*args))
File "/usr/local/bin/clip_read.py", line 41, in unwrap_self_cnt_clip_pos
return ClipReadInfo.collect_clip_positions_by_chrm(*arg, **kwarg)
File "/usr/local/bin/clip_read.py", line 311, in collect_clip_positions_by_chrm
xannotation.load_rmsk_annotation_with_extnd_with_lenth_cutoff(i_boundary_extnd, i_min_copy_len)
File "/usr/local/bin/x_annotation.py", line 330, in load_rmsk_annotation_with_extnd_with_lenth_cutoff
with open(self.sf_annotation) as fin_rmsk:
```

**Comment by B3rse** [comment]
it's linked to not finding the reference file, I would ignore all the cascade of errors since the starting point is the reference file mounted in the wrong place and not found by the program.
